# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO tzlaine/parser
    REF 875eb9e4aa18d1d5d9efa98bee578a0cd6073a0c
    SHA512 5fb62fe36525ecf1575223c6a3763cfe3d979c1e9d8e82a1b8bfd3ddfe8ba7052cc97e03f8f8bf50ac6c29469ce3d7006a6a134259d38ef29d05e14a104b8a11
    HEAD_REF develop
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
